# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: os-image
description: This is my personal OS image.

base-image: ghcr.io/blue-build/base-images/fedora-silverblue-nvidia
image-version: 43

modules:
  - from-file: base/common.yml
