# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: os-image
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 41 # latest is also supported if you want new updates ASAP

modules:
  - type: files
    files:
      - source: etc
        destination: /etc
      - source: usr
        destination: /usr

  # - type: containerfile
  #   snippets:
  #     - RUN chmod +x /etc/libvirt/hooks/daemon

  - type: gschema-overrides
    include:
      - zz1-defaults.gschema.override

  - type: rpm-ostree
    repos:
      - https://pkg.cloudflare.com/cloudflared-ascii.repo
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%OS_VERSION%/kylegospo-system76-scheduler-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/zeno/scrcpy/repo/fedora-%OS_VERSION%/scrcpy-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/nushell/repo/fedora-%OS_VERSION%/nushell-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/rockowitz/ddcutil/repo/fedora-%OS_VERSION%/ddcutil-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/matte-schwartz/sunshine/repo/fedora-%OS_VERSION%/sunshine-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      # - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-%OS_VERSION%/cosmic-epoch-fedora-%OS_VERSION%.repo
    install:
      - distrobox
      - podman-compose
      - neovim
      - cloudflared
      - adw-gtk3-theme
      # - code
      - restic
      - rclone
      - libadwaita
      # - nautilus-open-any-terminal
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-just-perfection
      # - gnome-shell-extension-blur-my-shell
      # - gnome-shell-extension-system76-scheduler
      # - system76-scheduler
      - scrcpy
      - setroubleshoot
      - flatpak-xdg-utils
      - syncthing
      - virt-install
      - libvirt-daemon-config-network
      - libvirt-daemon-kvm
      - qemu-kvm
      - virt-manager
      - virt-viewer
      - unrar
      - p7zip
      - gnome-monitor-config
      # - nushell
      - libgtop2-devel
      - lm_sensors
      - ddcutil
      - ddcui
      # for pano clipboard manager extension
      - libgda
      - libgda-sqlite
      - chntpw
      - bridge-utils
      - waydroid
      - lzip
      - tailscale
      - sunshine
      - usbmuxd
      - fish
      - zulucrypt
      - https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
      - gnome-shell-extension-gsconnect
      - webextension-gsconnect
      - nautilus-gsconnect
      # - livecd-tools
      # - cosmic-desktop
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      # - gnome-terminal-nautilus

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - org.mozilla.firefox
        # - dev.k8slens.OpenLens
        - tv.plex.PlexDesktop
        - net.lutris.Lutris
        - rest.insomnia.Insomnia
        - org.prismlauncher.PrismLauncher
        - org.qbittorrent.qBittorrent
        - com.redis.RedisInsight
        - page.kramo.Cartridges
        - com.usebottles.bottles
        - org.gnome.Geary
        - io.github.yuki_iptv.yuki-iptv
        - io.podman_desktop.PodmanDesktop
        - io.github.celluloid_player.Celluloid
        - com.valvesoftware.Steam
        - com.obsproject.Studio
        # - dev.lizardbyte.app.Sunshine
        - com.todoist.Todoist
        - com.github.tchx84.Flatseal
        - com.spotify.Client
        - com.discordapp.Discord
        # - dev.vencord.Vesktop
        - org.gnome.Loupe
        - org.gnome.Calculator
        - org.libreoffice.LibreOffice
        - org.gnome.Weather
        - org.gnome.Calendar
        - com.bitwarden.desktop
        - org.gnome.clocks
        - org.gnome.Evince
        - org.gimp.GIMP
        - org.pulseaudio.pavucontrol
        - com.github.marinm.songrec
        - io.dbeaver.DBeaverCommunity
        - io.github.Foldex.AdwSteamGtk
        - app.drey.Damask
        - it.mijorus.gearlever
        - dev.qwery.AddWater
        - com.github.johnfactotum.Foliate
        - net.sourceforge.jpdftweak.jPdfTweak
        - io.github.ungoogled_software.ungoogled_chromium
      # remove:
      #   - org.gnome.Totem

  # - type: default-flatpaks
  #   notify: true
  #   system:
  #     repo-url: https://valent.andyholmes.ca/valent.flatpakrepo
  #     repo-name: valent
  #     install:
  #       - ca.andyholmes.Valent

  # - type: bling
  #   install:
  #     - dconf-update-service

  # - type: brew

  # - type: akmods
  #   install:
  #     - v4l2loopback

  - type: gnome-extensions
    install:
      - Vitals
      - Airpod Battery Monitor
      - Compiz windows effect
      - Desktop Cube
      - Fullscreen Avoider
      - 4470 # Media Controls
      - Weather O'Clock
      - AppIndicator and KStatusNotifierItem Support
      - Just Perfection
      - 517 # Caffeine
      # - GSConnect
      - Brightness control using ddcutil
      - Grand Theft Focus

  - type: script
    scripts:
      - resticprofile.sh
      # - fonts.sh

  - type: systemd
    user:
      enabled:
        - syncthing
    system:
      enabled:
        - dconf-update.service
        - create-video-device.service
        - update.timer
        - libvirt-workaround.service
        - swtpm-workaround.service
        - libvirt-backup.service
        - libvirt-backup.timer
        - tailscaled.service

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add "Nerd Font" suffix.
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans
        - Fira Sans

  - type: initramfs

  - type: signing
