# image will be published to ghcr.io/<user>/<name>
name: os-image
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: gschema-overrides
    include:
      - zz1-defaults.gschema.override

  - type: files
    files:
      - usr:
          /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos:
      - https://pkg.cloudflare.com/cloudflared-ascii.repo
      - https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-%OS_VERSION%/ublue-os-staging-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%OS_VERSION%/kylegospo-system76-scheduler-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/zeno/scrcpy/repo/fedora-%OS_VERSION%/scrcpy-%OS_VERSION%.repo
    install:
      - distrobox
      - neovim
      - cloudflared
      - restic
      - rclone
      - libadwaita
      - nautilus-open-any-terminal
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-just-perfection
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-system76-scheduler
      - system76-scheduler
      - scrcpy
      - setroubleshoot
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - gnome-classic-session
      - gnome-tour
      - gnome-terminal-nautilus

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (system-wide)"
      install:
        - org.mozilla.firefox
        - dev.k8slens.OpenLens
        - tv.plex.PlexDesktop
        - net.lutris.Lutris
        - rest.insomnia.Insomnia
        - org.prismlauncher.PrismLauncher
        - org.qbittorrent.qBittorrent
        - com.redis.RedisInsight
        - hu.kramo.Cartridges
        - org.gnome.Geary
        - io.github.yuki_iptv.yuki-iptv
        - com.github.marhkb.Pods
        - org.gtk.Gtk3theme.adw-gtk3
        - org.gtk.Gtk3theme.adw-gtk3-dark
        - dev.lizardbyte.app.Sunshine
        - io.github.celluloid_player.Celluloid
        - com.valvesoftware.Steam
        - com.github.hluk.copyq
        - com.obsproject.Studio
        - dev.lizardbyte.app.Sunshine
        - com.todoist.Todoist
        - com.github.tchx84.Flatseal
        - com.spotify.Client
        - com.discordapp.Discord
        - org.gnome.Loupe
        - org.libreoffice.LibreOffice
      remove:
        - org.gnome.Totem

  # - type: default-flatpaks
  #   notify: true
  #   system:
  #     repo-url: https://nightly.gnome.org/gnome-nightly.flatpakrepo
  #     repo-name: gnome-nightly
  #     install:
  #       - org.gnome.Ptyxis.Devel

  # - type: default-flatpaks
  #   notify: true
  #   system:
  #     repo-url: https://valent.andyholmes.ca/valent.flatpakrepo
  #     repo-name: valent
  #     install:
  #       - ca.andyholmes.Valent

  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/akmods:main-39 /rpms/ /tmp/rpms
      - RUN curl -s -o- https://raw.githubusercontent.com/rafaelmardojai/firefox-gnome-theme/master/scripts/install-by-curl.sh | bash

  - type: akmods
    install:
      - v4l2loopback

  - type: script
    scripts:
      - appimagelauncher.sh
      - hide-terminal.sh
      # - firefox-gnome-theme.sh
      - resticprofile.sh

  - type: systemd
    user:
      enabled: syncthing.container
    system:
      enabled:
        - dconf-update.service
        - create-video-device.service

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add "Nerd Font" suffix.
        - NerdFontsSymbolsOnly
      google-fonts:
        - Roboto
        - Open Sans

  - type: signing
