#!/usr/bin/bash
set -euo pipefail

# Firefox HW Accel video with Nvidia drivers in Flatpak
# See https://github.com/elFarto/nvidia-vaapi-driver
# See https://github.com/ublue-os/bazzite/blob/0a19c73b220c53d76982928a5e840ca9155ed09a/system_files/desktop/shared/usr/libexec/bazzite-flatpak-manager#L92-L102
flatpak override \
    --system \
    --filesystem=host-os \
    --env=LIBVA_DRIVER_NAME=nvidia \
    --env=LIBVA_DRIVERS_PATH=/run/host/usr/lib64/dri \
    --env=LIBVA_MESSAGING_LEVEL=1 \
    --env=MOZ_DISABLE_RDD_SANDBOX=1 \
    --env=NVD_BACKEND=direct \
    org.mozilla.firefox

# enable wayland support for electron apps in flatpak
flatpak override --system --env=ELECTRON_OZONE_PLATFORM_HINT=auto

# disable wayland support for discord in flatpak (to fix keybinds not working)
flatpak override --system --env=ELECTRON_OZONE_PLATFORM_HINT=x11 com.discordapp.Discord